### ISSUE TITLE
Teacher Interview 1

### ISSUE THREAD

**Issue by TylerShago** [MTM6330-F18/Final--tsunami#4]

**Comment by schr0205** [comment]
Full Name: Katie Tremblay

Job Title: Professor/Coordinator

Email: tremblk3@algonquincollege.com

Phone (extension #): 6935

What courses do you teach? Currently just Design Foundations

Where did you go to school university, college, etc.)? Communications at Ottawa University and Interactive MultiMedia at Algonquin College.

Why did you become a teacher? I like helping people

How many years have you been a teacher? 7 years

Is there anything you wish you taught but can't? I have taught many subjects so probably not. I essentially think of something I want to teach, work hard at figuring it out and then teach it when I feel comfortable and confident in my skills.

Advice for future students: Be open minded and learn how to learn since this is a fast-past and every changing industry.
